services:
  arangodb:
    build: ./arangodb-docker
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: openSesame
  postgres:
    build: ./postgres-docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: project_sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
